### ISSUE TITLE
Verdaccio + Docker +Ldap Plugin

### ISSUE THREAD

**Issue by juanpicado** [snadn/docker-verdaccio-ldap#1]
I was working on this last week and I just saw your repo. Perhaps we can merge ideas.

https://github.com/verdaccio/docker-examples/tree/master/ldap-verdaccio

Would it make sense create an official  Docker image ready for LDAP within our organization?

**Comment by snadn** [comment]
@juanpicado I am very sorry, I only saw this news today. What should I do?

**Comment by juanpicado** [comment]
Hi, sorry the delay. 

I've been working on https://github.com/verdaccio/docker-examples/tree/master/ldap-verdaccio this example, but I saw you approach. It'd be cool to have your example in our repo or have both. What do you think?

**Comment by snadn** [comment]
Yes, I'm glad you added my example to your repo. I've added a simple readme to describe how I used it. If you still need what I do, you are welcome to point out.
